package Mensaje;

public enum TipoMensaje {
	MENSAJE_CONEXION, MENSAJE_LISTA_USR, MENSAJE_PEDIR, MENSAJE_PREPARADO_CS, MENSAJE_CERRAR_CONEXION, 
	MENSAJE_CONF_CONEXION, MENSAJE_CONF_LISTA_USR, MENSAJE_EMITIR, MENSAJE_PREPARADO_SC, 
	MENSAJE_CONF_CERRAR_CONEXION, MENSAJE_ANIADIR_PROD, MENSAJE_CONF_ANIADIR_PROD, MENSAJE_ELIMINAR_PROD, 
	MENSAJE_CONF_ELIMINAR_PROD, MENSAJE_MOD_PROD, MENSAJE_CONF_MOD_PROD, 

	MENSAJE_CLIENTES_CONEXION, MENSAJE_CLIENTES_CONF_CONEXION, MENSAJE_CLIENTES_PEDIR_PROD, MENSAJE_CLIENTES_CONF_PEDIR_PROD,
	MENSAJE_CLIENTES_CERRAR_CONEXION, MENSAJE_CLIENTES_CONF_CERRAR_CONEXION, MENSAJE_CLIENTES_CONF_ENVIAR_PROD,
	MENSAJE_ERROR

}
